package solutions;

public final class Problem_0002 {
	
	/*
	 * Problem: 
	 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
	 * the first 10 terms will be:
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
	 * find the sum of the even-valued terms.
	 */
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int sum = 0;
		int firstTerm = 1;
		int secondTerm = 2;
		int limit = 4_000_000;
		
		while(secondTerm < limit) {
			if (secondTerm % 2 == 0) {
				sum += secondTerm;
			}
			int nextTerm = firstTerm + secondTerm;
			firstTerm = secondTerm;
			secondTerm = nextTerm;
		}
		System.out.println(sum);
		
	}

}
